version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: wordpress_user
      PMA_PASSWORD: wordpress_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8082:80"  # Cambiado a 8082
    depends_on:
      - db
    networks:
      - my_network

  tor:
    image: dperson/torproxy
    container_name: tor
    volumes:
      - tor_data:/var/lib/tor
      - ./torrc:/etc/tor/torrc
    ports:
      - "9050:9050"  # Puerto SOCKS para redirigir tráfico
    networks:
      - my_network
    depends_on:
      - wordpress

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
  wordpress_data:
  tor_data:
